# Generated by Django 5.2.4 on 2025-07-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_order_total_alter_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
